/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BlogStatus = "archived" | "draft" | "published";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type JobGender = "any" | "female" | "male";

export type JobStatus = "archived" | "closed" | "draft" | "published";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface BlogCategory {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface Blog {
  authorId: number | null;
  categoryId: number | null;
  content: string;
  coverFileId: number | null;
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  seoDescription: string | null;
  seoKeywords: string | null;
  seoTitle: string | null;
  slug: string;
  status: Generated<BlogStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface ContactEntry {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  message: string;
  name: string;
  phone: string;
  updatedAt: Generated<Timestamp>;
}

export interface Email {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  isPrimary: Generated<boolean>;
  isVerified: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface JobApplication {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  medicalReportFileId: number | null;
  name: string;
  passportFileId: number | null;
  phone: string;
  preferredCountries: string | null;
  preferredPosition: string | null;
  resumeFileId: number | null;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface JobCategory {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  slug: string;
  updatedAt: Generated<Timestamp>;
}

export interface Job {
  categoryId: number | null;
  company: string | null;
  contractLength: string | null;
  createdAt: Generated<Timestamp>;
  description: string;
  documentsRequired: string | null;
  experience: string | null;
  fileId: number | null;
  gender: Generated<JobGender>;
  id: Generated<number>;
  isFeatured: Generated<boolean>;
  location: string | null;
  salary: string | null;
  slug: string;
  status: Generated<JobStatus>;
  title: string;
  updatedAt: Generated<Timestamp>;
  workingHours: string | null;
}

export interface Session {
  city: string | null;
  country: Generated<string>;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ip: string;
  region: string | null;
  updatedAt: Generated<Timestamp>;
  userAgent: string;
  userId: number;
}

export interface UploadedFile {
  fileType: string;
  id: Generated<number>;
  name: string;
  uploadedAt: Generated<Timestamp>;
  url: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
  password: string;
  phone: string | null;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  blogCategories: BlogCategory;
  blogs: Blog;
  contactEntries: ContactEntry;
  emails: Email;
  jobApplications: JobApplication;
  jobCategories: JobCategory;
  jobs: Job;
  sessions: Session;
  uploadedFiles: UploadedFile;
  users: User;
}
