/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminJobCategoriesRouteImport } from './routes/admin/job-categories'
import { Route as AdminJobApplicationsRouteImport } from './routes/admin/job-applications'
import { Route as AdminContactEntriesRouteImport } from './routes/admin/contact-entries'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'
import { Route as AdminBlogCategoriesRouteImport } from './routes/admin/blog-categories'
import { Route as MainSignupRouteImport } from './routes/_main/signup'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as MainLoginRouteImport } from './routes/_main/login'
import { Route as MainContactRouteImport } from './routes/_main/contact'
import { Route as MainBlogsRouteImport } from './routes/_main/blogs'
import { Route as MainApplyRouteImport } from './routes/_main/apply'
import { Route as MainAccountRouteImport } from './routes/_main/account'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as MainJobsIndexRouteImport } from './routes/_main/jobs.index'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiPublicSplatRouteImport } from './routes/api.public.$'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users_.new'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users_.$id'
import { Route as AdminJobsNewRouteImport } from './routes/admin/jobs_.new'
import { Route as AdminJobCategoriesNewRouteImport } from './routes/admin/job-categories_.new'
import { Route as AdminBlogsNewRouteImport } from './routes/admin/blogs_.new'
import { Route as AdminBlogCategoriesNewRouteImport } from './routes/admin/blog-categories_.new'
import { Route as MainSettingsDevicesRouteImport } from './routes/_main/settings_.devices'
import { Route as MainJobsSlugRouteImport } from './routes/_main/jobs.$slug'
import { Route as MainBlogsSlugRouteImport } from './routes/_main/blogs_.$slug'
import { Route as AdminJobsIdEditRouteImport } from './routes/admin/jobs_.$id.edit'
import { Route as AdminJobCategoriesIdEditRouteImport } from './routes/admin/job-categories_.$id.edit'
import { Route as AdminBlogsIdEditRouteImport } from './routes/admin/blogs_.$id.edit'
import { Route as AdminBlogCategoriesIdEditRouteImport } from './routes/admin/blog-categories_.$id.edit'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobCategoriesRoute = AdminJobCategoriesRouteImport.update({
  id: '/job-categories',
  path: '/job-categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobApplicationsRoute = AdminJobApplicationsRouteImport.update({
  id: '/job-applications',
  path: '/job-applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactEntriesRoute = AdminContactEntriesRouteImport.update({
  id: '/contact-entries',
  path: '/contact-entries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogCategoriesRoute = AdminBlogCategoriesRouteImport.update({
  id: '/blog-categories',
  path: '/blog-categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainSignupRoute = MainSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainContactRoute = MainContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBlogsRoute = MainBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainApplyRoute = MainApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAccountRoute = MainAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainJobsIndexRoute = MainJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSplatRoute = ApiPublicSplatRouteImport.update({
  id: '/api/public/$',
  path: '/api/public/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/users_/new',
  path: '/users/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users_/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsNewRoute = AdminJobsNewRouteImport.update({
  id: '/jobs_/new',
  path: '/jobs/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobCategoriesNewRoute = AdminJobCategoriesNewRouteImport.update({
  id: '/job-categories_/new',
  path: '/job-categories/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/blogs_/new',
  path: '/blogs/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogCategoriesNewRoute = AdminBlogCategoriesNewRouteImport.update({
  id: '/blog-categories_/new',
  path: '/blog-categories/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainSettingsDevicesRoute = MainSettingsDevicesRouteImport.update({
  id: '/settings_/devices',
  path: '/settings/devices',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainJobsSlugRoute = MainJobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBlogsSlugRoute = MainBlogsSlugRouteImport.update({
  id: '/blogs_/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => MainRouteRoute,
} as any)
const AdminJobsIdEditRoute = AdminJobsIdEditRouteImport.update({
  id: '/jobs_/$id/edit',
  path: '/jobs/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobCategoriesIdEditRoute =
  AdminJobCategoriesIdEditRouteImport.update({
    id: '/job-categories_/$id/edit',
    path: '/job-categories/$id/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminBlogsIdEditRoute = AdminBlogsIdEditRouteImport.update({
  id: '/blogs_/$id/edit',
  path: '/blogs/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogCategoriesIdEditRoute =
  AdminBlogCategoriesIdEditRouteImport.update({
    id: '/blog-categories_/$id/edit',
    path: '/blog-categories/$id/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof MainAboutRoute
  '/account': typeof MainAccountRoute
  '/apply': typeof MainApplyRoute
  '/blogs': typeof MainBlogsRoute
  '/contact': typeof MainContactRoute
  '/login': typeof MainLoginRoute
  '/settings': typeof MainSettingsRoute
  '/signup': typeof MainSignupRoute
  '/admin/blog-categories': typeof AdminBlogCategoriesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact-entries': typeof AdminContactEntriesRoute
  '/admin/job-applications': typeof AdminJobApplicationsRoute
  '/admin/job-categories': typeof AdminJobCategoriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/api/upload': typeof ApiUploadRoute
  '/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/$slug': typeof MainBlogsSlugRoute
  '/jobs/$slug': typeof MainJobsSlugRoute
  '/settings/devices': typeof MainSettingsDevicesRoute
  '/admin/blog-categories/new': typeof AdminBlogCategoriesNewRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/job-categories/new': typeof AdminJobCategoriesNewRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/jobs': typeof MainJobsIndexRoute
  '/admin/blog-categories/$id/edit': typeof AdminBlogCategoriesIdEditRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/job-categories/$id/edit': typeof AdminJobCategoriesIdEditRoute
  '/admin/jobs/$id/edit': typeof AdminJobsIdEditRoute
}
export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/account': typeof MainAccountRoute
  '/apply': typeof MainApplyRoute
  '/blogs': typeof MainBlogsRoute
  '/contact': typeof MainContactRoute
  '/login': typeof MainLoginRoute
  '/settings': typeof MainSettingsRoute
  '/signup': typeof MainSignupRoute
  '/admin/blog-categories': typeof AdminBlogCategoriesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact-entries': typeof AdminContactEntriesRoute
  '/admin/job-applications': typeof AdminJobApplicationsRoute
  '/admin/job-categories': typeof AdminJobCategoriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/api/upload': typeof ApiUploadRoute
  '/': typeof MainIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blogs/$slug': typeof MainBlogsSlugRoute
  '/jobs/$slug': typeof MainJobsSlugRoute
  '/settings/devices': typeof MainSettingsDevicesRoute
  '/admin/blog-categories/new': typeof AdminBlogCategoriesNewRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/job-categories/new': typeof AdminJobCategoriesNewRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/jobs': typeof MainJobsIndexRoute
  '/admin/blog-categories/$id/edit': typeof AdminBlogCategoriesIdEditRoute
  '/admin/blogs/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/job-categories/$id/edit': typeof AdminJobCategoriesIdEditRoute
  '/admin/jobs/$id/edit': typeof AdminJobsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/account': typeof MainAccountRoute
  '/_main/apply': typeof MainApplyRoute
  '/_main/blogs': typeof MainBlogsRoute
  '/_main/contact': typeof MainContactRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/signup': typeof MainSignupRoute
  '/admin/blog-categories': typeof AdminBlogCategoriesRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/contact-entries': typeof AdminContactEntriesRoute
  '/admin/job-applications': typeof AdminJobApplicationsRoute
  '/admin/job-categories': typeof AdminJobCategoriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/$': typeof ApiSplatRoute
  '/api/upload': typeof ApiUploadRoute
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_main/blogs_/$slug': typeof MainBlogsSlugRoute
  '/_main/jobs/$slug': typeof MainJobsSlugRoute
  '/_main/settings_/devices': typeof MainSettingsDevicesRoute
  '/admin/blog-categories_/new': typeof AdminBlogCategoriesNewRoute
  '/admin/blogs_/new': typeof AdminBlogsNewRoute
  '/admin/job-categories_/new': typeof AdminJobCategoriesNewRoute
  '/admin/jobs_/new': typeof AdminJobsNewRoute
  '/admin/users_/$id': typeof AdminUsersIdRoute
  '/admin/users_/new': typeof AdminUsersNewRoute
  '/api/public/$': typeof ApiPublicSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_main/jobs/': typeof MainJobsIndexRoute
  '/admin/blog-categories_/$id/edit': typeof AdminBlogCategoriesIdEditRoute
  '/admin/blogs_/$id/edit': typeof AdminBlogsIdEditRoute
  '/admin/job-categories_/$id/edit': typeof AdminJobCategoriesIdEditRoute
  '/admin/jobs_/$id/edit': typeof AdminJobsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/about'
    | '/account'
    | '/apply'
    | '/blogs'
    | '/contact'
    | '/login'
    | '/settings'
    | '/signup'
    | '/admin/blog-categories'
    | '/admin/blogs'
    | '/admin/contact-entries'
    | '/admin/job-applications'
    | '/admin/job-categories'
    | '/admin/jobs'
    | '/admin/users'
    | '/api/$'
    | '/api/upload'
    | '/'
    | '/admin/'
    | '/blogs/$slug'
    | '/jobs/$slug'
    | '/settings/devices'
    | '/admin/blog-categories/new'
    | '/admin/blogs/new'
    | '/admin/job-categories/new'
    | '/admin/jobs/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/api/public/$'
    | '/api/rpc/$'
    | '/jobs'
    | '/admin/blog-categories/$id/edit'
    | '/admin/blogs/$id/edit'
    | '/admin/job-categories/$id/edit'
    | '/admin/jobs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/account'
    | '/apply'
    | '/blogs'
    | '/contact'
    | '/login'
    | '/settings'
    | '/signup'
    | '/admin/blog-categories'
    | '/admin/blogs'
    | '/admin/contact-entries'
    | '/admin/job-applications'
    | '/admin/job-categories'
    | '/admin/jobs'
    | '/admin/users'
    | '/api/$'
    | '/api/upload'
    | '/'
    | '/admin'
    | '/blogs/$slug'
    | '/jobs/$slug'
    | '/settings/devices'
    | '/admin/blog-categories/new'
    | '/admin/blogs/new'
    | '/admin/job-categories/new'
    | '/admin/jobs/new'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/api/public/$'
    | '/api/rpc/$'
    | '/jobs'
    | '/admin/blog-categories/$id/edit'
    | '/admin/blogs/$id/edit'
    | '/admin/job-categories/$id/edit'
    | '/admin/jobs/$id/edit'
  id:
    | '__root__'
    | '/_main'
    | '/admin'
    | '/_main/about'
    | '/_main/account'
    | '/_main/apply'
    | '/_main/blogs'
    | '/_main/contact'
    | '/_main/login'
    | '/_main/settings'
    | '/_main/signup'
    | '/admin/blog-categories'
    | '/admin/blogs'
    | '/admin/contact-entries'
    | '/admin/job-applications'
    | '/admin/job-categories'
    | '/admin/jobs'
    | '/admin/users'
    | '/api/$'
    | '/api/upload'
    | '/_main/'
    | '/admin/'
    | '/_main/blogs_/$slug'
    | '/_main/jobs/$slug'
    | '/_main/settings_/devices'
    | '/admin/blog-categories_/new'
    | '/admin/blogs_/new'
    | '/admin/job-categories_/new'
    | '/admin/jobs_/new'
    | '/admin/users_/$id'
    | '/admin/users_/new'
    | '/api/public/$'
    | '/api/rpc/$'
    | '/_main/jobs/'
    | '/admin/blog-categories_/$id/edit'
    | '/admin/blogs_/$id/edit'
    | '/admin/job-categories_/$id/edit'
    | '/admin/jobs_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiPublicSplatRoute: typeof ApiPublicSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/job-categories': {
      id: '/admin/job-categories'
      path: '/job-categories'
      fullPath: '/admin/job-categories'
      preLoaderRoute: typeof AdminJobCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/job-applications': {
      id: '/admin/job-applications'
      path: '/job-applications'
      fullPath: '/admin/job-applications'
      preLoaderRoute: typeof AdminJobApplicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contact-entries': {
      id: '/admin/contact-entries'
      path: '/contact-entries'
      fullPath: '/admin/contact-entries'
      preLoaderRoute: typeof AdminContactEntriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog-categories': {
      id: '/admin/blog-categories'
      path: '/blog-categories'
      fullPath: '/admin/blog-categories'
      preLoaderRoute: typeof AdminBlogCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/signup': {
      id: '/_main/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof MainSignupRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/contact': {
      id: '/_main/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MainContactRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/blogs': {
      id: '/_main/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof MainBlogsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/apply': {
      id: '/_main/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof MainApplyRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/account': {
      id: '/_main/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof MainAccountRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/jobs/': {
      id: '/_main/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof MainJobsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$': {
      id: '/api/public/$'
      path: '/api/public/$'
      fullPath: '/api/public/$'
      preLoaderRoute: typeof ApiPublicSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users_/new': {
      id: '/admin/users_/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users_/$id': {
      id: '/admin/users_/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs_/new': {
      id: '/admin/jobs_/new'
      path: '/jobs/new'
      fullPath: '/admin/jobs/new'
      preLoaderRoute: typeof AdminJobsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/job-categories_/new': {
      id: '/admin/job-categories_/new'
      path: '/job-categories/new'
      fullPath: '/admin/job-categories/new'
      preLoaderRoute: typeof AdminJobCategoriesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blogs_/new': {
      id: '/admin/blogs_/new'
      path: '/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog-categories_/new': {
      id: '/admin/blog-categories_/new'
      path: '/blog-categories/new'
      fullPath: '/admin/blog-categories/new'
      preLoaderRoute: typeof AdminBlogCategoriesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/settings_/devices': {
      id: '/_main/settings_/devices'
      path: '/settings/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof MainSettingsDevicesRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/jobs/$slug': {
      id: '/_main/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof MainJobsSlugRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/blogs_/$slug': {
      id: '/_main/blogs_/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof MainBlogsSlugRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/admin/jobs_/$id/edit': {
      id: '/admin/jobs_/$id/edit'
      path: '/jobs/$id/edit'
      fullPath: '/admin/jobs/$id/edit'
      preLoaderRoute: typeof AdminJobsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/job-categories_/$id/edit': {
      id: '/admin/job-categories_/$id/edit'
      path: '/job-categories/$id/edit'
      fullPath: '/admin/job-categories/$id/edit'
      preLoaderRoute: typeof AdminJobCategoriesIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blogs_/$id/edit': {
      id: '/admin/blogs_/$id/edit'
      path: '/blogs/$id/edit'
      fullPath: '/admin/blogs/$id/edit'
      preLoaderRoute: typeof AdminBlogsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog-categories_/$id/edit': {
      id: '/admin/blog-categories_/$id/edit'
      path: '/blog-categories/$id/edit'
      fullPath: '/admin/blog-categories/$id/edit'
      preLoaderRoute: typeof AdminBlogCategoriesIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainAccountRoute: typeof MainAccountRoute
  MainApplyRoute: typeof MainApplyRoute
  MainBlogsRoute: typeof MainBlogsRoute
  MainContactRoute: typeof MainContactRoute
  MainLoginRoute: typeof MainLoginRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainSignupRoute: typeof MainSignupRoute
  MainIndexRoute: typeof MainIndexRoute
  MainBlogsSlugRoute: typeof MainBlogsSlugRoute
  MainJobsSlugRoute: typeof MainJobsSlugRoute
  MainSettingsDevicesRoute: typeof MainSettingsDevicesRoute
  MainJobsIndexRoute: typeof MainJobsIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainAccountRoute: MainAccountRoute,
  MainApplyRoute: MainApplyRoute,
  MainBlogsRoute: MainBlogsRoute,
  MainContactRoute: MainContactRoute,
  MainLoginRoute: MainLoginRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainSignupRoute: MainSignupRoute,
  MainIndexRoute: MainIndexRoute,
  MainBlogsSlugRoute: MainBlogsSlugRoute,
  MainJobsSlugRoute: MainJobsSlugRoute,
  MainSettingsDevicesRoute: MainSettingsDevicesRoute,
  MainJobsIndexRoute: MainJobsIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminBlogCategoriesRoute: typeof AdminBlogCategoriesRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminContactEntriesRoute: typeof AdminContactEntriesRoute
  AdminJobApplicationsRoute: typeof AdminJobApplicationsRoute
  AdminJobCategoriesRoute: typeof AdminJobCategoriesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogCategoriesNewRoute: typeof AdminBlogCategoriesNewRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminJobCategoriesNewRoute: typeof AdminJobCategoriesNewRoute
  AdminJobsNewRoute: typeof AdminJobsNewRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminBlogCategoriesIdEditRoute: typeof AdminBlogCategoriesIdEditRoute
  AdminBlogsIdEditRoute: typeof AdminBlogsIdEditRoute
  AdminJobCategoriesIdEditRoute: typeof AdminJobCategoriesIdEditRoute
  AdminJobsIdEditRoute: typeof AdminJobsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBlogCategoriesRoute: AdminBlogCategoriesRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminContactEntriesRoute: AdminContactEntriesRoute,
  AdminJobApplicationsRoute: AdminJobApplicationsRoute,
  AdminJobCategoriesRoute: AdminJobCategoriesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogCategoriesNewRoute: AdminBlogCategoriesNewRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminJobCategoriesNewRoute: AdminJobCategoriesNewRoute,
  AdminJobsNewRoute: AdminJobsNewRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminBlogCategoriesIdEditRoute: AdminBlogCategoriesIdEditRoute,
  AdminBlogsIdEditRoute: AdminBlogsIdEditRoute,
  AdminJobCategoriesIdEditRoute: AdminJobCategoriesIdEditRoute,
  AdminJobsIdEditRoute: AdminJobsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiPublicSplatRoute: ApiPublicSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
