/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main/route'
import { Route as MainIndexImport } from './routes/_main/index'
import { Route as MainContactImport } from './routes/_main/contact'
import { Route as MainAboutImport } from './routes/_main/about'
import { Route as MainJobsIndexImport } from './routes/_main/jobs.index'
import { Route as MainJobsSlugImport } from './routes/_main/jobs.$slug'

// Create/Update Routes

const MainRouteRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRoute,
} as any)

const MainIndexRoute = MainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)

const MainContactRoute = MainContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRouteRoute,
} as any)

const MainAboutRoute = MainAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)

const MainJobsIndexRoute = MainJobsIndexImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => MainRouteRoute,
} as any)

const MainJobsSlugRoute = MainJobsSlugImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => MainRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutImport
      parentRoute: typeof MainRouteImport
    }
    '/_main/contact': {
      id: '/_main/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MainContactImport
      parentRoute: typeof MainRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexImport
      parentRoute: typeof MainRouteImport
    }
    '/_main/jobs/$slug': {
      id: '/_main/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof MainJobsSlugImport
      parentRoute: typeof MainRouteImport
    }
    '/_main/jobs/': {
      id: '/_main/jobs/'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof MainJobsIndexImport
      parentRoute: typeof MainRouteImport
    }
  }
}

// Create and export the route tree

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainContactRoute: typeof MainContactRoute
  MainIndexRoute: typeof MainIndexRoute
  MainJobsSlugRoute: typeof MainJobsSlugRoute
  MainJobsIndexRoute: typeof MainJobsIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainContactRoute: MainContactRoute,
  MainIndexRoute: MainIndexRoute,
  MainJobsSlugRoute: MainJobsSlugRoute,
  MainJobsIndexRoute: MainJobsIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof MainRouteRouteWithChildren
  '/about': typeof MainAboutRoute
  '/contact': typeof MainContactRoute
  '/': typeof MainIndexRoute
  '/jobs/$slug': typeof MainJobsSlugRoute
  '/jobs': typeof MainJobsIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof MainAboutRoute
  '/contact': typeof MainContactRoute
  '/': typeof MainIndexRoute
  '/jobs/$slug': typeof MainJobsSlugRoute
  '/jobs': typeof MainJobsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/about': typeof MainAboutRoute
  '/_main/contact': typeof MainContactRoute
  '/_main/': typeof MainIndexRoute
  '/_main/jobs/$slug': typeof MainJobsSlugRoute
  '/_main/jobs/': typeof MainJobsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/about' | '/contact' | '/' | '/jobs/$slug' | '/jobs'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/contact' | '/' | '/jobs/$slug' | '/jobs'
  id:
    | '__root__'
    | '/_main'
    | '/_main/about'
    | '/_main/contact'
    | '/_main/'
    | '/_main/jobs/$slug'
    | '/_main/jobs/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_main"
      ]
    },
    "/_main": {
      "filePath": "_main/route.tsx",
      "children": [
        "/_main/about",
        "/_main/contact",
        "/_main/",
        "/_main/jobs/$slug",
        "/_main/jobs/"
      ]
    },
    "/_main/about": {
      "filePath": "_main/about.tsx",
      "parent": "/_main"
    },
    "/_main/contact": {
      "filePath": "_main/contact.tsx",
      "parent": "/_main"
    },
    "/_main/": {
      "filePath": "_main/index.tsx",
      "parent": "/_main"
    },
    "/_main/jobs/$slug": {
      "filePath": "_main/jobs.$slug.tsx",
      "parent": "/_main"
    },
    "/_main/jobs/": {
      "filePath": "_main/jobs.index.tsx",
      "parent": "/_main"
    }
  }
}
ROUTE_MANIFEST_END */
